#!/usr/bin/env bash
###############################################################################
# generate.sh
#
# Interactive generator for an ACT topology YAML file.
#
# Asks for a serial prefix + spine/leaf counts, then emits a full-mesh
# topology with pinned serial_number + system_mac_address on every node so
# CVaaS keeps device identity across redeploys.
#
# After running this, upload + deploy the file in the ACT UI, then run
# ./onboard.sh to push the CVaaS onboarding config.
###############################################################################

set -euo pipefail

# shellcheck source=_common.sh
source "$(dirname "${BASH_SOURCE[0]}")/_common.sh"

DEFAULT_SPINES=2
DEFAULT_LEAVES=4
DEFAULT_EOS_VERSION="4.32.2F"

MAX_SPINES=9      # spines use IPs 192.168.0.11-.19
MAX_LEAVES=99     # leaves use IPs 192.168.0.21-.119 (cap is paranoia, not a hard limit)

###############################################################################
# load cached config + prompt
###############################################################################
SPINE_COUNT=""
LEAF_COUNT=""
EOS_VERSION=""

load_config

echo
echo "Topology parameters:"
# SERIAL_PREFIX is intentionally never cached — coworkers MUST set their own
# so serial namespaces don't collide on the shared ACT tenant.
prompt SERIAL_PREFIX "Serial prefix"     "example:bsmith"
prompt SPINE_COUNT   "Number of spines"  "${DEFAULT_SPINES}"
prompt LEAF_COUNT    "Number of leaves"  "${DEFAULT_LEAVES}"
prompt EOS_VERSION   "EOS version"       "${DEFAULT_EOS_VERSION}"

# validate
if ! [[ "${SPINE_COUNT}" =~ ^[1-9][0-9]*$ ]] || (( SPINE_COUNT > MAX_SPINES )); then
    echo "ERROR: spine count must be 1-${MAX_SPINES}, got '${SPINE_COUNT}'." >&2
    exit 1
fi
if ! [[ "${LEAF_COUNT}" =~ ^[1-9][0-9]*$ ]] || (( LEAF_COUNT > MAX_LEAVES )); then
    echo "ERROR: leaf count must be 1-${MAX_LEAVES}, got '${LEAF_COUNT}'." >&2
    exit 1
fi
if ! [[ "${SERIAL_PREFIX}" =~ ^[A-Za-z0-9]+$ ]]; then
    echo "ERROR: serial prefix must be alphanumeric (no dashes/spaces), got '${SERIAL_PREFIX}'." >&2
    exit 1
fi

save_config
echo

###############################################################################
# decide output filename and confirm
###############################################################################
TODAY="$(date +%Y-%m-%d)"
OUT_FILE="${PROJECT_DIR}/topology-${SERIAL_PREFIX}-${TODAY}.yml"
OUT_NAME="${OUT_FILE##*/}"

echo "Will write ${OUT_NAME}"
echo "  ${SPINE_COUNT} spine(s), ${LEAF_COUNT} leaf/leaves, EOS ${EOS_VERSION}, full mesh"
if [[ -e "${OUT_FILE}" ]]; then
    echo "  (file already exists — will be overwritten)"
fi
echo
read -r -p "Continue? [y/N] " ans
case "${ans}" in [Yy]*) ;; *) echo "Aborted."; exit 1 ;; esac

###############################################################################
# emit the YAML
###############################################################################
{
    cat <<HEADER
###############################################################################
# Generated by generate.sh on ${TODAY}.
#
# Filename convention: topology-<prefix>-<YYYY-MM-DD>.yml — ACT requires
# unique filenames across the tenant. Re-run generate.sh on another day to
# get a fresh filename.
#
# Switch identity is pinned via serial_number + system_mac_address so devices
# keep the same identity in CVaaS across redeploys.
###############################################################################

veos:
  username: cvpadmin
  password: cvp123!
  version: ${EOS_VERSION}

nodes:

  ###########################################################################
  # Spines
  ###########################################################################
HEADER

    for (( i=1; i<=SPINE_COUNT; i++ )); do
        cat <<NODE

  - spine${i}:
      node_type: veos
      ip_addr: 192.168.0.$((10 + i))/24
      serial_number: ${SERIAL_PREFIX}-spine${i}
      system_mac_address: 00:1c:73:00:01:$(printf '%02x' "${i}")
      ztp: false
NODE
    done

    cat <<'LEAFHEADER'

  ###########################################################################
  # Leaves
  ###########################################################################
LEAFHEADER

    for (( i=1; i<=LEAF_COUNT; i++ )); do
        cat <<NODE

  - leaf${i}:
      node_type: veos
      ip_addr: 192.168.0.$((20 + i))/24
      serial_number: ${SERIAL_PREFIX}-leaf${i}
      system_mac_address: 00:1c:73:00:02:$(printf '%02x' "${i}")
      ztp: false
NODE
    done

    cat <<'LINKHEADER'

###############################################################################
# Data-plane links (spine <-> leaf full mesh)
#   spine[i] Ethernet[j] <-> leaf[j] Ethernet[i]
###############################################################################
links:
LINKHEADER

    for (( s=1; s<=SPINE_COUNT; s++ )); do
        for (( l=1; l<=LEAF_COUNT; l++ )); do
            echo "  - connection: [spine${s}:Ethernet${l}, leaf${l}:Ethernet${s}]"
        done
        if (( s < SPINE_COUNT )); then
            echo ""
        fi
    done
} > "${OUT_FILE}"

echo
echo "Wrote ${OUT_NAME}"
echo "Next:  upload + deploy in the ACT UI, then run ./onboard.sh"
